-- generated by github copilot
CREATE TABLE IF NOT EXISTS product (
    product_id SERIAL PRIMARY KEY,
    sales INTEGER NOT NULL DEFAULT 0,
    sku_id INTEGER,
    completed INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO product (product_id, sales, sku_id, completed, created_at, updated_at)
SELECT
    i AS product_id,
    (random() * 100)::INTEGER AS sales,
    (random() * 1000)::INTEGER AS sku_id,
    (random() * 10)::INTEGER AS completed,
    NOW() AS created_at,
    NOW() AS updated_at
FROM generate_series(1, 10) AS s(i);


-- generated by github copilot
INSERT INTO ruancat_obj_table (create_time, modified_time, version, remark, modified_by, creator, content)
SELECT
    NOW(),
    NOW(),
    floor(random() * 10)::int,
    LEFT(md5(random()::text), 20),
    LEFT(md5(random()::text), 10),
    LEFT(md5(random()::text), 10),
    LEFT(md5(random()::text), 128)
FROM generate_series(1, 10);
